{"uuid": "112dd95a-74ac-4ae4-a3a2-2f14e9da2f59", "children": ["1c77e355-5ec6-4441-9d1a-7c39afd6d921"], "befores": [{"name": "function_user", "status": "broken", "statusDetails": {"message": "httpx.RemoteProtocolError: Server disconnected without sending a response.\n", "trace": "  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/fixtures/users.py\", line 56, in function_user\n    response = public_users_client.create_user(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/clients/users/public_users_client.py\", line 24, in create_user\n    response = self.create_user_api(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/clients/users/public_users_client.py\", line 21, in create_user_api\n    return self.post(\"/api/v1/users\", json=request.model_dump(by_alias=True))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/clients/api_client.py\", line 44, in post\n    return self.client.post(url, json=json, data=data, files=files)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 1144, in post\n    return self.request(\n           ^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 825, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 914, in send\n    response = self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 1014, in _send_single_request\n    response = transport.handle_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py\", line 249, in handle_request\n    with map_httpcore_exceptions():\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py\", line 118, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "steps": [{"name": "Create user", "status": "broken", "statusDetails": {"message": "httpx.RemoteProtocolError: Server disconnected without sending a response.\n", "trace": "  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/clients/users/public_users_client.py\", line 21, in create_user_api\n    return self.post(\"/api/v1/users\", json=request.model_dump(by_alias=True))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/clients/api_client.py\", line 44, in post\n    return self.client.post(url, json=json, data=data, files=files)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 1144, in post\n    return self.request(\n           ^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 825, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 914, in send\n    response = self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 1014, in _send_single_request\n    response = transport.handle_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py\", line 249, in handle_request\n    with map_httpcore_exceptions():\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py\", line 118, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "steps": [{"name": "Make POST request to '/api/v1/users'", "status": "broken", "statusDetails": {"message": "httpx.RemoteProtocolError: Server disconnected without sending a response.\n", "trace": "  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/clients/api_client.py\", line 44, in post\n    return self.client.post(url, json=json, data=data, files=files)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 1144, in post\n    return self.request(\n           ^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 825, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 914, in send\n    response = self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_client.py\", line 1014, in _send_single_request\n    response = transport.handle_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py\", line 249, in handle_request\n    with map_httpcore_exceptions():\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"/Users/macbookrik/PycharmProjects/autotests-api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py\", line 118, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "parameters": [{"name": "url", "value": "'/api/v1/users'"}, {"name": "json", "value": "{'email': 'brentgriffin@example.com', 'password': '_9VfEWi2BU', 'lastName': 'Williams', 'firstName': 'Mike', 'middleName': 'Matthew'}"}, {"name": "data", "value": "None"}, {"name": "files", "value": "None"}], "start": 1751277100526, "stop": 1751277100529}], "parameters": [{"name": "request", "value": "CreateUserRequestSchema(email='brentgriffin@example.com', password='_9VfEWi2BU', last_name='Williams', first_name='Mike', middle_name='Matthew')"}], "start": 1751277100526, "stop": 1751277100530}], "start": 1751277100525, "stop": 1751277100530}], "start": 1751277100525, "stop": 1751277100582}